@startuml
skinparam actorStyle awesome

title "Analyse Video Stream Diragram"

participant Glasses as G #LightSalmon
participant Application as S #lightblue

G -> S : send the main video stream


alt time to analyse a new frame 
    S -> S : recover a frame from the main video stream 
    S -> S : try recognize the faces in the frame

    alt face recognized
        S -> S : modify the frame by adding the name of the recognized face    
    else face not recognized
        S -> S : dont modify the frame 
    end

    S -> S : store the modified frame
    S -> G : send the modified frame

else NOT time to analyse a new frame
    S -> G : send the last analysed frame stored
end

@enduml
